### ISSUE TITLE
change backbone

### ISSUE THREAD

**Issue by kp-1** [FateScript/CenterNet-better#10]
老哥你好，如果我想在你的代码基础之上做一些修改，比如更换backbone，那我应该怎么做，你能在你有空的时候给一些指导吗，先谢谢老哥了

**Comment by FateScript** [comment]
> 老哥你好，如果我想在你的代码基础之上做一些修改，比如更换backbone，那我应该怎么做，你能在你有空的时候给一些指导吗，先谢谢老哥了

首先你可以仿照[这个文件](https://github.com/FateScript/CenterNet-better/blob/master/dl_lib/network/backbone/resnet_backbone.py)写一下你自己的backbone，
然后在你的network.py里面的build_backbone改成你自己的backbone就行了，可以参考这个[文件](https://github.com/FateScript/CenterNet-better/blob/master/playground/centernet.res18.coco.512size/net.py#L9)

基本上就这些

**Comment by kp-1** [comment]
好的，谢谢

**Comment by deep-practice** [comment]
果然比原版清晰多了~
