### ISSUE TITLE
Could you please provide the link for pretrained model of res50?

### ISSUE THREAD

**Issue by Bovey0809** [FateScript/CenterNet-better#12]
Thank you for your great work.
As what has been mentioned in the repo, the centernet is really hard to converge.
And I also read your closed issues , seems that you are using torchvision pretrained models. But when I tried to load the torchvision pretrained r50 model, the weights can't be loaded, the same as detectron2.
If it's possible, please provide the link of res50 pretrained model. Thanks a lot.
And also for people who are struggling from the converge problem, lower down the lr may not be much helpful.

**Comment by Bovey0809** [comment]
After following the code, I found the default value for pretrained is True, which means the resnet50 is already loaded.

**Comment by FateScript** [comment]
> After following the code, I found the default value for pretrained is True, which means the resnet50 is already loaded.

Yes, detectron2 use its own pre-trained model and this repo uses torchvision pretrained model, that's the difference.

**Comment by Bovey0809** [comment]
So that the pretrained torchvision model has been already loaded, right, if I use the default config file (playground/res50/config.py).
