### ISSUE TITLE
How to solve this red error when using PyCharm

### ISSUE THREAD

**Issue by songyuc** [FateScript/CenterNet-better#15]
Hi, guys,
I am learning this repo and using PyCharm.
But I meet a problem that there is a red error when checking the code in PyCharm, although the code seems to run normally.
It shows like this,
![图片](https://user-images.githubusercontent.com/27288110/83374486-5a495f00-a3fe-11ea-9bfd-ed8e405e655a.png)
Could please tell me how to fix this?

Your answer and idea will be appreciated!

**Comment by FateScript** [comment]
> Hi, guys,
> I am learning this repo and using PyCharm.
> But I meet a problem that there is a red error when checking the code in PyCharm, although the code seems to run normally.
> It shows like this,
> ![图片](https://user-images.githubusercontent.com/27288110/83374486-5a495f00-a3fe-11ea-9bfd-ed8e405e655a.png)
> Could please tell me how to fix this?
> 
> Your answer and idea will be appreciated!

Because pycharm could not find config file, actually config is used in playground. This error doesn't matter, so you could ignore this.
