### ISSUE TITLE
What is the meaning of "gaussian_iou" in the dataset?

### ISSUE THREAD

**Issue by songyuc** [FateScript/CenterNet-better#17]
Hi, guys,
I am learning about CenterNet these days, and I want to know what is the meaning of `gaussian_iou = 0.7` for the dataset?

Any idea or answer will be appreciated!

**Comment by FateScript** [comment]
> Hi, guys,
> I am learning about CenterNet these days, and I want to know what is the meaning of `gaussian_iou = 0.7` for the dataset?
> 
> Any idea or answer will be appreciated!

please provide code link, thank u
