### ISSUE TITLE
[Documentation Request] performance gains

### ISSUE THREAD

**Issue by austinmw** [FateScript/CenterNet-better#19]
Hi, thanks for this repo. If you would, could you explain what implementation details you attribute the performance gains you've measure to?

**Comment by FateScript** [comment]
> Hi, thanks for this repo. If you would, could you explain what implementation details you attribute the performance gains you've measure to?

Thanks for your question. I’ve replied a similar [issue](https://github.com/FateScript/CenterNet-better/issues/1) in which you might find the answer you want.
