### ISSUE TITLE
相对于原版的改进

### ISSUE THREAD

**Issue by dl8207531** [FateScript/CenterNet-better#20]
ResNet-18 map：29.8 确实厉害
请问下这里使用了dcn吗？从代码里没看到
再就是打高斯核和数据增强同原版有改进吗？

**Comment by FateScript** [comment]
请参考这个[issue](https://github.com/FateScript/CenterNet-better/issues/1)

使用了dcn的，在[这里](https://github.com/FateScript/CenterNet-better/blob/master/dl_lib/network/head/centernet_deconv.py#L20)可以看到

**Comment by dl8207531** [comment]
了解，谢谢
