### ISSUE TITLE
请问一下网络的后处理在哪个部分

### ISSUE THREAD

**Issue by GYxiaOH** [FateScript/CenterNet-better#22]
rt。。。我看了下test里直接把model结果输出了？不是应该有个maxpool操作加上topk排序吗....我没有找到这个方面的实现？是有什么考虑吗？

**Comment by FateScript** [comment]
[here](https://github.com/FateScript/CenterNet-better/blob/master/dl_lib/network/generator/centernet_decode.py#L86)

**Comment by GYxiaOH** [comment]
@FateScript 好的谢谢，您是在哪里调用这个函数的呢？我昨天追踪到[here](https://github.com/FateScript/CenterNet-better/blob/7336530c7e50a462a9b5c6cda486a5faa04320d0/dl_lib/evaluation/evaluator.py#L122)这里，就看到直接网络输出了。。。

**Comment by FateScript** [comment]
在[这里](https://github.com/FateScript/CenterNet-better/blob/master/dl_lib/network/generator/centernet_decode.py#L30)，请善用github的检索功能，谢谢

**Comment by GYxiaOH** [comment]
啊，你误解我的意思了....不过我知道了 我没看到        if not self.training:
            return self.inference(images)这句话，现在逻辑清楚了！感谢您的帮助！
