### ISSUE TITLE
install error     gcc -std=gnu99: No such file or directory

### ISSUE THREAD

**Issue by GYxiaOH** [FateScript/CenterNet-better#23]
在gcc 4.9 5.2 cuda 9.0 10.1下均会报错：
  ERROR: Command errored out with exit status 1:
     command: /search/odin/hongyuan/anaconda3/envs/py13/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/search/odin/hongyuan/CenterNet-better/setup.py'"'"'; __file__='"'"'/search/odin/hongyuan/CenterNet-better/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /search/odin/hongyuan/CenterNet-better/
    Complete output (19 lines):
    running develop
    running egg_info
    writing dl_lib.egg-info/PKG-INFO
    writing dependency_links to dl_lib.egg-info/dependency_links.txt
    writing requirements to dl_lib.egg-info/requires.txt
    writing top-level names to dl_lib.egg-info/top_level.txt
    reading manifest file 'dl_lib.egg-info/SOURCES.txt'
    writing manifest file 'dl_lib.egg-info/SOURCES.txt'
    running build_ext
    building 'dl_lib._C' extension
    gcc -std=gnu99 -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/search/odin/hongyuan/CenterNet-better/dl_lib/layers -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include/TH -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include/THC -I/search/odin/hongyuan/cuda-9.0/include -I/search/odin/hongyuan/anaconda3/envs/py13/include/python3.7m -c /search/odin/hongyuan/CenterNet-better/dl_lib/layers/vision.cpp -o build/temp.linux-x86_64-3.7/search/odin/hongyuan/CenterNet-better/dl_lib/layers/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
    gcc -std=gnu99 -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/search/odin/hongyuan/CenterNet-better/dl_lib/layers -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include/TH -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include/THC -I/search/odin/hongyuan/cuda-9.0/include -I/search/odin/hongyuan/anaconda3/envs/py13/include/python3.7m -c /search/odin/hongyuan/CenterNet-better/dl_lib/layers/ROIAlign/ROIAlign_cpu.cpp -o build/temp.linux-x86_64-3.7/search/odin/hongyuan/CenterNet-better/dl_lib/layers/ROIAlign/ROIAlign_cpu.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    cc1plus: warning: command line option ‘-std=gnu99’ is valid for C/ObjC but not for C++
    /search/odin/hongyuan/cuda-9.0/bin/nvcc -DWITH_CUDA -I/search/odin/hongyuan/CenterNet-better/dl_lib/layers -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include/TH -I/search/odin/hongyuan/anaconda3/envs/py13/lib/python3.7/site-packages/torch/include/THC -I/search/odin/hongyuan/cuda-9.0/include -I/search/odin/hongyuan/anaconda3/envs/py13/include/python3.7m -c /search/odin/hongyuan/CenterNet-better/dl_lib/layers/ROIAlign/ROIAlign_cuda.cu -o build/temp.linux-x86_64-3.7/search/odin/hongyuan/CenterNet-better/dl_lib/layers/ROIAlign/ROIAlign_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -ccbin=gcc -std=gnu99 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1 -gencode=arch=compute_61,code=sm_61 -std=c++11
    gcc -std=gnu99: No such file or directory
    error: command '/search/odin/hongyuan/cuda-9.0/bin/nvcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /search/odin/hongyuan/anaconda3/envs/py13/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/search/odin/hongyuan/CenterNet-better/setup.py'"'"'; __file__='"'"'/search/odin/hongyuan/CenterNet-better/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by FateScript** [comment]
What's your pytorch version or could you please provide more info and make sure you set up the right env

**Comment by benywon** [comment]
Have you resolved this problem?
