### ISSUE TITLE
About the initialization model

### ISSUE THREAD

**Issue by MingtaoFu** [FateScript/CenterNet-better#24]
In the original paper of CenterNet, the authors finetune the model from ExtremeNet-trained model instead of the ImageNet pretrained model or training from scratch. Which strategy is used in this repo and do you know the difference of performance among these strategies?
Thank you very much!

**Comment by FateScript** [comment]
The original paper of CenterNet use finetuned weights for Hourglass, not ResNet backbone. This repo only uses ResNet backbone only and there is no need to finetune these backbones.
