### ISSUE TITLE
生成真值index

### ISSUE THREAD

**Issue by kaiopen** [FateScript/CenterNet-better#25]
看起来可以用中文交流？
在 `dl_lib/network/generator/centernet_gt.py` 的 `CenterNetGT` 类 的 `generate` 方法中，
```
gt_index[:num_boxes] = centers_int[..., 1] * output_size[0] + centers_int[..., 0]
```
按理解，output_size[0] 是输出特征图的高度，output_size[1] 是宽度吧？centers_int[1] 是 box 中心点的 y，那这块的 index 计算是不是应该是 
```
centers_int[..., 1] * output_size[1] + centers_int[..., 0]
```
虽然因为out_size 的高宽一样，对结果没有影响。

**Comment by FateScript** [comment]
看了一下，的确是有bug的，现在[这个地方](https://github.com/FateScript/CenterNet-better/blob/master/dl_lib/network/generator/centernet_gt.py#L39)已经fix了，感谢issue
