### ISSUE TITLE
4GPU training with resnet18-centernet

### ISSUE THREAD

**Issue by LovPe** [FateScript/CenterNet-better#26]
Hi 
I tried to train CenterNet resnet18 with 4GPU and batchsize 128. The network can not converge. 
Did you met the seem problem?

**Comment by WJ1214** [comment]
author suppose you have 150GB Memory for training when you use batchsize 128, i guess you need reduce your batchsize

**Comment by LovPe** [comment]
@WJ1214 thanks for reply
The converge problem means the training become NAN after several iterations( < 100), I do not met any memory issue. 
I use default settings except num-gpu is 4.

**Comment by FateScript** [comment]
> @WJ1214 thanks for reply
> The converge problem means the training become NAN after several iterations( < 100), I do not met any memory issue.
> I use default settings except num-gpu is 4.

change your batchsize and lr while change your num-gpus, the default setting is used for 8 gpu.
