### ISSUE TITLE
error in modulated_deformable_col2im_coord_cuda: invalid device function

### ISSUE THREAD

**Issue by kritohyh** [FateScript/CenterNet-better#32]
Hello, could you help me?
I am running the code with the following problem:
```
error in modulated_deformable_col2im_coord_cuda: invalid device function
error in modulated_deformable_col2im_cuda: invalid device function
error in modulated_deformable_im2col_cuda: invalid device function
```
Environmental information that the program prints:
--------------------  --------------------------------------------------
sys.platform          linux
Python                3.7.9 (default, Aug 31 2020, 12:42:55) [GCC 7.3.0]
Numpy                 1.19.4
dl_lib Compiler       GCC 5.4
dl_lib CUDA Compiler  10.0
dl_lib_ENV_MODULE     <not set>
PyTorch               1.4.0+cu100
PyTorch Debug Build   False
torchvision           0.5.0+cu100
CUDA available        True
GPU 0,1,2,3,4,5,6,7   GeForce RTX 2080 Ti
CUDA_HOME             /usr/local/cuda
NVCC                  Cuda compilation tools, release 10.0, V10.0.130
Pillow                8.0.1
cv2                   4.4.0
--------------------  --------------------------------------------------
PyTorch built with:
  - GCC 7.3
  - Intel(R) Math Kernel Library Version 2019.0.4 Product Build 20190411 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v0.21.1 (Git Hash 7d2fd500bc78936d1d648ca713b901012f470dbc)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CUDA Runtime 10.0
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.1
  - Build settings: BLAS=MKL, BUILD_NAMEDTENSOR=OFF, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow, DISABLE_NUMA=1, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_STATIC_DISPATCH=OFF,

**Comment by bkj** [comment]
+1 -- I'm getting the same error -- any ideas on how to fix?

**Comment by FateScript** [comment]
This error occurred using cuda 10.0. Please **upgrade your cuda**, thanks.
