### ISSUE TITLE
输入尺寸问题

### ISSUE THREAD

**Issue by CodeGod-J** [FateScript/CenterNet-better#35]
你好，我在centernet.py line153下面打印up_fmap的尺寸（使用test_net.py）
     

      up_fmap = self.upsample(features)

      print(up_fmap.size())
，发现输出为 
torch.Size([1, 64, 128, 168])
torch.Size([1, 64, 128, 168])
torch.Size([1, 64, 112, 168])
torch.Size([1, 64, 128, 168])
torch.Size([1, 64, 168, 96])
torch.Size([1, 64, 168, 160])
torch.Size([1, 64, 168, 128])
torch.Size([1, 64, 112, 168])
torch.Size([1, 64, 136, 168])
torch.Size([1, 64, 168, 112])
torch.Size([1, 64, 168, 112])

这部分尺寸输出不应该是128吗，我没有找到输入resize为512那部分代码？请问这个复现不是基于固定尺寸（输入512，输出128）的吗?

**Comment by FateScript** [comment]
这个复现是固定尺寸（512， 512）的，改变size的code在[这里](https://github.com/FateScript/CenterNet-better/blob/master/dl_lib/data/transforms/transform_gen.py#L149)

**Comment by CodeGod-J** [comment]
非常感谢你的及时回复，但是我追踪output_size为centernet.py inference函数中的`new_h, new_w = (h | 31) + 1, (w | 31) + 1`
计算得到的，其中的h和w是 batch input images的尺寸，我又看了代码，训练时候是从512到128，测试时候是否是原图进行测试的呢？

**Comment by FateScript** [comment]
[here](https://github.com/FateScript/CenterNet-better/blob/972dbf2882375d54ec0e06ada21f39baaa997f0c/dl_lib/data/transforms/extend_transform.py#L294)

**Comment by CodeGod-J** [comment]
谢谢，我发现是测试的时候没有transform（因为我的图片比较大，所以inference time过长，所以才产生了困惑）。麻烦了，新年快乐。
