### ISSUE TITLE
About padding operation(迷之操作) during inference!

### ISSUE THREAD

**Issue by jiangzhengkai** [FateScript/CenterNet-better#36]
Feng wang:

I tried to understand padding operations during inference but failed. You should give an explanation.

Following the original CenterNet implementation, replacing the padding with CenterAffine, mAP drops to 28% compared with original 34.4% performance!

You are expected to give the reason!

**Comment by FateScript** [comment]
[code here](https://github.com/FateScript/CenterNet-better/blob/972dbf2882375d54ec0e06ada21f39baaa997f0c/dl_lib/network/generator/centernet_decode.py#L63) might be helpful. During inference, image padding is applied on four sides, and a new affine matrix is calculated. Did you forget such an operation?

**Comment by jiangzhengkai** [comment]
@FateScript [code](https://github.com/FateScript/CenterNet-better/blame/972dbf2882375d54ec0e06ada21f39baaa997f0c/dl_lib/network/generator/centernet_decode.py#L78) aims to generate affine matrix to map the regressed box results to image size. Because the regressed boxes downsample 4 according to [code](https://github.com/FateScript/CenterNet-better/blame/972dbf2882375d54ec0e06ada21f39baaa997f0c/dl_lib/network/generator/centernet_gt.py#L35), thus we need to map regressed boxes to origin image size. I still can not figure out the reason why using image padding and why the performance drops when using cv2.warpAffine to resize the original image.

**Comment by FateScript** [comment]
Did you retrain your model since you are using a different augmentation?

**Comment by PeizeSun** [comment]
@FateScript @jiangzhengkai
Hi~ I follow you guys for a very long time! It is very exciting to see you two battle~

However, I am a little confused about: Is there difference between image padding applied on **four sides** and **only right bottom sides**? Why does CenterNet apply image padding on four sides?

**Comment by jiangzhengkai** [comment]
@PeizeSun Amazing to talk here with feng wang.

**Comment by jiangzhengkai** [comment]
> Did you retrain your model since you are using a different augmentation?

When training, CenterAffine is used to do augmentation, no padding. So, why do we need to retrain the model?

**Comment by FateScript** [comment]
> > Did you retrain your model since you are using a different augmentation?
> 
> When training, CenterAffine is used to do augmentation, no padding. So, why do we need to retrain the model?

Since you are using a different aug which might bring difference between training and infernce.

**Comment by jiangzhengkai** [comment]
got it!
