### ISSUE TITLE
what net inside tools/test_net.py?

### ISSUE THREAD

**Issue by jinfagang** [FateScript/CenterNet-better#4]
test_net.py

https://github.com/FateScript/CenterNet-better/blob/7336530c7e50a462a9b5c6cda486a5faa04320d0/tools/test_net.py#L27

https://github.com/FateScript/CenterNet-better/blob/7336530c7e50a462a9b5c6cda486a5faa04320d0/tools/test_net.py#L34

are u sure these line can be imported? from where?

**Comment by FateScript** [comment]
> test_net.py
> 
> https://github.com/FateScript/CenterNet-better/blob/7336530c7e50a462a9b5c6cda486a5faa04320d0/tools/test_net.py#L27
> 
> https://github.com/FateScript/CenterNet-better/blob/7336530c7e50a462a9b5c6cda486a5faa04320d0/tools/test_net.py#L34
> 
> are u sure these line can be imported? from where?

Train_net and test_net are used for dl_train and dl_test comand.

Files named net.py and config.py could be found in playground, e.g. [here](https://github.com/FateScript/CenterNet-better/tree/master/playground/centernet.res18.coco.512size).

**Comment by jinfagang** [comment]
thanks, found it.

Does there any visiualize demo on  any model?

**Comment by FateScript** [comment]
> thanks, found it.
> 
> Does there any visiualize demo on any model?

Sorry, I didn't try it, but I believe that visualize code in decectron2 will also work here, I might support it in the future.
