### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by EnricoBeltramo** [FateScript/CenterNet-better#40]
I use a Conda environment where I installed pytorch 1.3.1 gpu, but I have follow error when I start setup.py

    ERROR: Command errored out with exit status 1:
     command: /home/ulix/anaconda3/envs/centerenetbetter/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/setup.py'"'"'; __file__='"'"'/media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/
    Complete output (17 lines):
    running develop
    running egg_info
    writing dl_lib.egg-info/PKG-INFO
    writing dependency_links to dl_lib.egg-info/dependency_links.txt
    writing requirements to dl_lib.egg-info/requires.txt
    writing top-level names to dl_lib.egg-info/top_level.txt
    reading manifest file 'dl_lib.egg-info/SOURCES.txt'
    writing manifest file 'dl_lib.egg-info/SOURCES.txt'
    running build_ext
    building 'dl_lib._C' extension
    gcc -pthread -B /home/ulix/anaconda3/envs/centerenetbetter/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/dl_lib/layers -I/home/ulix/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/lib/include -I/home/ulix/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/lib/include/TH -I/home/ulix/anaconda3/envs/CenterNet/lib/python3.6/site-packages/torch/lib/include/THC -I/home/ulix/anaconda3/envs/centerenetbetter/include/python3.6m -c /media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/dl_lib/layers/vision.cpp -o build/temp.linux-x86_64-3.6/media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/dl_lib/layers/vision.o -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/dl_lib/layers/vision.cpp:5:10: fatal error: torch/types.h: No such file or directory
     #include <torch/types.h>
              ^~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ulix/anaconda3/envs/centerenetbetter/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/setup.py'"'"'; __file__='"'"'/media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n(centerenetbetter) ulix@ulix-Strix-17-GL703GE:/media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better$ ^Cfor full command output.

**Comment by FateScript** [comment]
```
/media/ulix/DATA1/Progetti/Inventio/InMindSO/CenterNet-better/dl_lib/layers/vision.cpp:5:10: fatal error: torch/types.h: No such file or directory
```
maybe your torch is not installed correctly. Such an error might  happen if you are using a wrong version of Pytorch.

**Comment by FateScript** [comment]
close this issue due to no more reply during 2 weeks.
