### ISSUE TITLE
ModuleNotFoundError: No module named 'config'

### ISSUE THREAD

**Issue by Wang-Qinyu** [FateScript/CenterNet-better#43]
Traceback (most recent call last):
  File "/home/wangqinyu/STR/CenterNet-better/tools/test_net.py", line 27, in <module>
    from config import config
ModuleNotFoundError: No module named 'config'

**Comment by fengqian-wei** [comment]
change the address in  playground/centernet.resxx.coco.512size
cd playground/centernet.res18.coco.512size

**Comment by Wang-Qinyu** [comment]
Thank you very much for your letter. I will test it according to the tips you gave. In particular, I look forward to your model can be applied to other datasets except not just COCO.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FateScript/CenterNet-better"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 中午12:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [FateScript/CenterNet-better] ModuleNotFoundError: No module named 'config' (#43)





 
change the address in  playground/centernet.resxx.coco.512size
 cd playground/centernet.res18.coco.512size

**Comment by fengqian-wei** [comment]
I think you need change the dataSet label into  COCO format, and then can train model.
