### ISSUE TITLE
How to adjust checkpoint frequency

### ISSUE THREAD

**Issue by hoangxtr** [FateScript/CenterNet-better#47]
Thanks to your repo, i've trained model successfull on my custom dataset. It's very helpfull and very well. However, like the title, i don't know how to set the checkpoint frequency. Can you help me. Thanks

**Comment by hoangxtr** [comment]
I've known the answer, thanks everyone

**Comment by toastedbaguatte** [comment]
Hi hello! can i ask how did you train the model on your own custom dataset?
