### ISSUE TITLE
No module named 'brainpp'

### ISSUE THREAD

**Issue by lzrobots** [FateScript/CenterNet-better#5]
Hi I just had the following error when testing the res18 downloaded model

```
CenterNet-better/dl_lib/utils/file_io.py", line 13, in <module>
    from brainpp import oss
ModuleNotFoundError: No module named 'brainpp'
```
I have all the dependencies installed.
Would you know what is the problem?

**Comment by FateScript** [comment]
> Hi I just had the following error when testing the res18 downloaded model
> 
> ```
> CenterNet-better/dl_lib/utils/file_io.py", line 13, in <module>
>     from brainpp import oss
> ModuleNotFoundError: No module named 'brainpp'
> ```
> 
> I have all the dependencies installed.
> Would you know what is the problem?

You are using an old version file_io.py, please use the current file_io.py in this repo.
