### ISSUE TITLE
gcc error？

### ISSUE THREAD

**Issue by kike-0304** [FateScript/CenterNet-better#50]
I try to gcc4.9.3/5.5/7.0, but all of them cannot building. Can you give me a hand?
Thank you very much!
cuda 10.1, torch1.4

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    /home/cc631/code/Dilated-FPN/CenterNet-better/dl_lib/layers/vision.cpp:4:10: fatal error: cuda_runtime_api.h: 
     #include <cuda_runtime_api.h>
              ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/cc631/anaconda3/envs/pytorch1.4/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/cc631/hailong/code/Dilated-FPN/CenterNet-better/setup.py'"'"'; __file__='"'"'/home/cc631/hailong/code/Dilated-FPN/CenterNet-better/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

**Comment by FateScript** [comment]
What's your pytorch version?
