### ISSUE TITLE
no modules

### ISSUE THREAD

**Issue by yy2yy** [FateScript/CenterNet-better#53]
Hi, thank you for your great work, but i have some questions:
(1)from config import config   where is the "config" module？
(2)from net import build_model  where is the "net" module?
Could you share the modules with me? Thank you very much!

**Comment by FateScript** [comment]
For example, files are [here](https://github.com/FateScript/CenterNet-better/tree/master/playground/centernet.res101.coco.512size).
Plz enter the working directory first.

**Comment by yy2yy** [comment]
> For example, files are [here](https://github.com/FateScript/CenterNet-better/tree/master/playground/centernet.res101.coco.512size). Plz enter the working directory first.

Oh, Thank you!
