### ISSUE TITLE
unable to run "dl_train --num-gpus 1"

### ISSUE THREAD

**Issue by toastedbaguatte** [FateScript/CenterNet-better#54]
I am currently attempting to run CenterNet on my laptop of RTX 3050. However, after following the steps and typing "dl_train --num-gpus 1" into the terminal, there were multiple error messages.

**soft link to /CenterNet-better/playground/centernet.res18.coco.512size
ln: failed to create symbolic link 'log': File exists
Command Line Args: Namespace(resume=False, eval_only=False, num_gpus=1, num_machines=1, machine_rank=0, dist_url='tcp://127.0.0.1:50152', opts=[])
check /CenterNet-better/playground/centernet.res18.coco.512size
Traceback (most recent call last):
  File "/home/zhengyang/CenterNet-better/tools/train_net.py", line 119, in <module>
    launch(
  File "/home/zhengyang/CenterNet-better/dl_lib/engine/launch.py", line 53, in launch
    main_func(*args)
  File "/home/zhengyang/CenterNet-better/tools/train_net.py", line 79, in main
    cfg, logger = default_setup(config, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhengyang/CenterNet-better/dl_lib/engine/defaults.py", line 95, in default_setup
    PathManager.mkdirs(output_dir)
  File "/home/zhengyang/CenterNet-better/dl_lib/utils/file_io.py", line 448, in mkdirs
    return PathManager.__get_path_handler(path)._mkdirs(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhengyang/CenterNet-better/dl_lib/utils/file_io.py", line 254, in _mkdirs
    os.makedirs(path, exist_ok=True)**

When checking the code itself in vscode, some of the issues included reportMissingImports within the file train_net.py under tools. It says that Import "net" can't be resolved, Pylance. 
![image](https://github.com/FateScript/CenterNet-better/assets/155293525/29a2c11e-1cce-4a61-a88b-9b8b15317cde)

May I ask is there an error in the directory from the errors or is there any other set ups that I missed? Thank you :)

  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 215, in makedirs
  File "<frozen os>", line 225, in makedirs

PermissionError: [Errno 13] Permission denied: '/CenterNet-better'

**Comment by FateScript** [comment]
Please run `dl_train` under dir like [this](https://github.com/FateScript/CenterNet-better/tree/master/playground/centernet.res50.coco.512size). You will find net and config there.

**Comment by toastedbaguatte** [comment]
> Please run `dl_train` under dir like [this](https://github.com/FateScript/CenterNet-better/tree/master/playground/centernet.res50.coco.512size). You will find net and config there.


Hi there! thanks for replying me :) Actually the command dl_train was ran after entering the centrenet.res50.coco.512size directory. However there was still multiple errors as shown in the post.

Do you have any advice on what to do next? Thank you!

**Comment by toastedbaguatte** [comment]
> Please run `dl_train` under dir like [this](https://github.com/FateScript/CenterNet-better/tree/master/playground/centernet.res50.coco.512size). You will find net and config there.

Hi FateScript, here is an image for further clarification. Thank you!

![image](https://github.com/FateScript/CenterNet-better/assets/155293525/83b7dce3-17ac-4db0-a624-c9f0bfa266fa)
