### ISSUE TITLE
cannot import name 'config' from 'config'

### ISSUE THREAD

**Issue by wly-ai-bj** [FateScript/CenterNet-better#7]
when i run the file train_net.py, I met the error :
cannot import name 'config' from 'config'.
How can I solve it?

**Comment by FateScript** [comment]
> when i run the file train_net.py, I met the error :
> cannot import name 'config' from 'config'.
> How can I solve it?

please enter the playground and find which one you want to train, for example, for resnet-50,
run:
```shell
cd playground/centernet.res50.coco.512size
dl_train --num-gpus 8
```

**Comment by wly-ai-bj** [comment]
dl_train --num-gpus 8, can run correctly. But I want to debug the train_net.py file to understand the code completely。

**Comment by FateScript** [comment]
> dl_train --num-gpus 8, can run correctly. But I want to debug the train_net.py file to understand the code completely。

You may use 1-gpu to run and set NUM_WORKERS=0 in config.py, then you can use embed or ipdb.set_trace to debug.

Or 
after setting breakpoint, use command provided below :
```shell
dl_train --num-gpus 1  SOLVER.IMS_PER_BATCH 2 DATALOADER.NUM_WORKERS 0
````
