### ISSUE TITLE
How to train custom dataset about this model?

### ISSUE THREAD

**Issue by FFudi** [FateScript/CenterNet-better#9]
How to set the path and config when i want to train the model through a custom dataset changed to detectron2 format ??

**Comment by FFudi** [comment]
Solved the problem. Thank you for providing a good model.

**Comment by Soulempty** [comment]
@FateScript 
how to train the model with custom data?thanks

**Comment by FateScript** [comment]
> @FateScript
> how to train the model with custom data?thanks

The same with detectron2, you may read [this documentation](https://detectron2.readthedocs.io/tutorials/datasets.html) for more information.

**Comment by Soulempty** [comment]
Thanks!
